# specify which database and adapter to use for which environment

development:
  adapter: sqlite3
  database: db/task_manager_development

test:
  adapter: sqlite3
  database: db/task_manager_test

production:
  adapter: sqlite3
  database: db/task_manager_production
